from dataclasses import dataclass, field
from typing import List, Optional, Dict, Any, Union
import numpy as np

@dataclass
class ProteinSequence:
    """Represents a raw protein sequence generated by an LM."""
    id: str
    sequence: str
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __len__(self):
        return len(self.sequence)

@dataclass
class StructurePrediction:
    """Represents the output of a folding tool (e.g., AlphaFold, ESMFold)."""
    sequence_id: str
    pdb_path: Optional[str]  # Path to PDB file if saved
    plddt: Optional[np.ndarray] = None # Per-residue confidence scores
    mean_plddt: float = 0.0
    pae: Optional[np.ndarray] = None # Predicted Aligned Error
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    @property
    def is_folded(self) -> bool:
        """Heuristic to check if folding was successful/attempted."""
        return self.mean_plddt > 0

@dataclass
class ScoredSequence:
    """A sequence that has been folded and scored with energy/confidence."""
    sequence: ProteinSequence
    structure: StructurePrediction
    energy_score: Optional[float] = None # Rosetta energy or similar
    stability_score: float = 0.0 # Composite score (higher is better)
    is_stable: bool = False
    metadata: Dict[str, Any] = field(default_factory=dict)

@dataclass
class PreferencePair:
    """A pair of sequences labeled with preference (winner vs loser)."""
    winner: ScoredSequence
    loser: ScoredSequence
    source: str = "random" # e.g., "random", "mutation", "hard_negative"
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "winner_seq": self.winner.sequence.sequence,
            "loser_seq": self.loser.sequence.sequence,
            "winner_score": self.winner.stability_score,
            "loser_score": self.loser.stability_score,
            "source": self.source,
            "winner_id": self.winner.sequence.id,
            "loser_id": self.loser.sequence.id
        }
